### ISSUE TITLE
Non-Functional requirements

### ISSUE THREAD

**Issue by zcgda** [zcgda/giphygram#110]
- [x] Platform/device support - all versions will be targeted a browser-based web app viewable both on a desktop or laptop #107
- [x] User capacity - The solution needs to cater for a maximum of 200 concurrent users at any point in time #108
- [x] Accessibility - Compliant with Section 508 #109
