### ISSUE TITLE
Manage Roles-based Users

### ISSUE THREAD

**Issue by zcgda** [zcgda/giphygram#47]
- [ ] Create User #38
- [x] Upon user a/c creation, pre-populate work folders with one titled "My Bookmarks" (i.e. user can use/rename/delete) #39
- [x] Update Role of User #40
- [ ] Disable/Enable User #41
- [x] Update User Details #42
- [x] Reset Password #43
- [ ] Initial Preset Roles and Permissions #44
- [x] Finalise Preset Roles and Permissions #45
- [x] Ability to manage roles and permissions #46
