### ISSUE TITLE
Manage Endpoints

### ISSUE THREAD

**Issue by zcgda** [zcgda/giphygram#55]
- [x] Configure Endpoint #51
- [x] Enable / Disable endpoint #52
- [x] Grant user access to endpoint #53
- [ ] Revoke user access to endpoint #54
