### ISSUE TITLE
File Search

### ISSUE THREAD

**Issue by zcgda** [zcgda/giphygram#63]
- [ ] Drill down (explorer style) #56
- [ ] Simple search - single input box keyword(s) #57
- [x] Advanced Search #58
- [ ] Search history #59
- [x] Search file content #60
- [x] Search file meta-data #61
- [x] Search custom user-defined meta-data #62
