### ISSUE TITLE
View Search Results

### ISSUE THREAD

**Issue by zcgda** [zcgda/giphygram#70]
- [x] View results (list of files) #64
- [x] Save search #65
- [x] Add File/Folder to My File Basket #66
- [x] Add File/Folder to Work Folder #67
- [x] Sortable search results #68
- [x] Toggle View (List / Tiles) #69
