### ISSUE TITLE
View File Details

### ISSUE THREAD

**Issue by zcgda** [zcgda/giphygram#75]
- [x] View details of file #71
- [x] Add File/Folder to My File Basket #72
- [x] Add File/Folder to Work Folder #73
- [x] Actions #74
