### ISSUE TITLE
My Saved Searches

### ISSUE THREAD

**Issue by zcgda** [zcgda/giphygram#79]
- [x] Rename / Delete Saved Search #76
- [x] Repeat Saved Search #77
- [x] Share/unshare Saved Search #78
