### ISSUE TITLE
My Work Folders

### ISSUE THREAD

**Issue by zcgda** [zcgda/giphygram#90]
- [ ] Create Work Folder #82
- [ ] Delete Work Folder #83
- [ ] Rename Work Folder #84
- [x] Update Work Folder #85
- [ ] My File Basket #86
- [ ] Bulk Actions #87
- [ ] Share/unshare Custom Work Folder with user #88
- [x] Share/unshare Custom Work Folder with team #89
